### PR TITLE
Add translation

### PR DESCRIPTION
**Pull request by Nemiroff**

### CODE REVIEW

**Comment by Tolriq** [comment]
Thanks a lot.

When I'll add new strings, I must add them to all translation files or there's automatic fallback ?

**Comment by Nemiroff** [comment]
Yes

**Comment by Tolriq** [comment]
Yes for automatic fallback ?

**Comment by Nemiroff** [comment]
Yes, automatic fallback

**Comment by Tolriq** [comment]
Ok thanks again.

**Pull request merged**
