### PR TITLE
Fix error after rename urlresolve plugin

### PR DESCRIPTION
**Pull request by Nemiroff**
Correcting the error after renaming the plugin urlresolve. In order for it to be updated, users had to increase the release number

### CODE REVIEW

**Comment by Tolriq** [comment]
Thanks

**Comment by Nemiroff** [comment]
And you have already installed the addon script.module.urlresolver? If yes, then there will be no error.

**Comment by Tolriq** [comment]
No I do not have the other one installed. But I have no choice I can't ask users to add another repository specially one with Team Kodi saying so much hate about :)

Anyway have you ever see: https://yatse.tv/redmine/issues/1260 ?

**Comment by Nemiroff** [comment]
A possible problem is the use of the OSMC. 
And I was not thinking just of the plug-ins to take the required functionality, and not the entire plug-in completely?

**Comment by Tolriq** [comment]
Sorry I do not understand your last sentence.

**Comment by Nemiroff** [comment]
Take the source code and add it to the plugin. How to pyaes in urlresolve.
Look. Now your plugin calls Youtube-dl with a link to the video, and causes an error. What is different from if you use the old version of Yates and share the same link, then Kodi will immediately apply to the Youtube-dl plugin and give the same error.

**Comment by Tolriq** [comment]
I can't call directly youtube dl from Yatse that's the whole point. Well I can but can't get the result.
I'm not going the addon way with pleasure, I just have no choice to bypass JSON limitations and bugs :(

Kodi does not apply youtube-dl to shared links automatically this is not how it works.

**Pull request merged**
